### ISSUE TITLE
(Question) Are there any live public projects using this or open source projects implementing this library?

### ISSUE THREAD

**Issue by parkgrrr** [sshaw/ddex#12]
I have a friend who works for a non profit in Puerto Rico who has been cataloging music from the island.  Pandora is asking for a DDEX file and he is not sure if he needs to create them by hand, or if there is a better way.  They are very limited in resources so I'm trying to help out.  I am wondering if there are any public apps or services that could help.

**Comment by sshaw** [comment]
Hi,

> Are there any live public projects using this or open source projects implementing this library

I don't know of anything public using this but I assume based on PRs/issues there are some private. 

> They are very limited in resources so I'm trying to help out. I am wondering if there are any public apps or services that could help.

I know of this, but I haven't used it: https://github.com/willm/DDEXUI 
I just tried to install on OS X but ran into some dependency issues. 

Let me know if you find anything else. 

If you tell me the the DDEX spec version he needs to create and the elements/attributes that Pandora is requiring I can put together an example of how to create the XML programmatically using this library.

**Comment by parkgrrr** [comment]
I really appreciate your help!  I will refer my friend to the DDEXUI project and maybe we can get it working.  If not I will reach out to you, and maybe with your example I could put together a script or something.

**Comment by sshaw** [comment]
Okay, let me know how it goes.

**Comment by sshaw** [comment]
@parkgrrr now there is this DDEX GUI: https://metadatagui.com/ern/new
