### ISSUE TITLE
ERN v312

### ISSUE THREAD

**Issue by parndt** [sshaw/ddex#7]
Hi @sshaw,

We have to read the following XML:

``` xml
<ern:NewReleaseMessage xmlns:ern="http://ddex.net/xml/2010/ern-main/312"
                       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                       xsi:schemaLocation="http://ddex.net/xml/2010/ern-main/312 http://ddex.net/xml/2010/ern-main/312/ern-main.xsd"
                       MessageSchemaVersionId="2010/ern-main/312">
```

As you can see, the MessageSchemaVersionId is `2010/ern-main/312`.

How much work do you think it'd be for us to write support for this version, and which steps should we follow in doing so?

Thanks!
Phil

**Comment by sshaw** [comment]
The easiest thing to do is to try to have it parsed as ERN 3.3 (the earliest version supported by this library). Obviously there may be some (BIG) downsides to this but it's worth a shot. Checkout [this section](https://github.com/sshaw/ddex#specification-version-detection) of the docs to see how.

The better route is full support. This may be easy as 95% of the Ruby code is generated automatically from the schema.  See [CONTRIBUTING](https://github.com/sshaw/ddex/blob/master/CONTRIBUTING.md) for instructions. Let me know if anything is not clear or if you have any other questions

**Comment by sshaw** [comment]
Any luck with with the `version` option @parndt?

**Comment by parndt** [comment]
Oh yeah!! See #8 :smile:

**Comment by sshaw** [comment]
Hey great thanks! Would it be possible to add a spec or two?
